# Generated by Django 2.1.7 on 2019-03-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yolo', '0002_city_events_places_places_of_interest_restaurant_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
