# Generated by Django 2.1.7 on 2019-03-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yolo', '0003_auto_20190327_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
