# Generated by Django 2.1.7 on 2019-04-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yolo', '0004_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='places',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='places_of_interest',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='place_name',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.DeleteModel(
            name='Places_Of_Interest',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
