# Generated by Django 2.1.7 on 2019-04-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Yolo', '0005_auto_20190406_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('exists', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yolo.City')),
            ],
        ),
        migrations.CreateModel(
            name='Places_Of_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot', models.CharField(max_length=100)),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yolo.Places')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('dist', models.FloatField()),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yolo.Places')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='place_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yolo.Places'),
        ),
    ]
