# Generated by Django 2.1.7 on 2019-04-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yolo', '0006_auto_20190406_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='places',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='places_of_interest',
            name='place_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place_name',
        ),
        migrations.AddField(
            model_name='city',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.DeleteModel(
            name='Places_Of_Interest',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
