# Generated by Django 2.1.7 on 2019-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_hotels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='city',
            new_name='city_name',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='double_room_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='double_room_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='executive_room_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='executive_room_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='single_room_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='single_room_number',
            field=models.IntegerField(default=0),
        ),
    ]
