# Generated by Django 2.1.7 on 2019-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20190413_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='room_type',
            field=models.CharField(blank=True, choices=[('single_room', 'Single Room'), ('double_room', 'Double Room'), ('executive_room', 'Executive Room')], max_length=50),
        ),
    ]
