# Generated by Django 2.1.7 on 2019-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_hotels_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, choices=[('single_room', 'Single Room'), ('double_room', 'Double Room'), ('executive_room', 'Executive Room')], max_length=50)),
                ('number_of_rooms', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='room_type',
        ),
    ]
