# Generated by Django 2.1.7 on 2019-04-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20190413_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='address',
            field=models.CharField(default='some address', max_length=200),
        ),
    ]
