# Generated by Django 2.1.7 on 2019-04-14 13:52

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_hotels_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_input',
            name='booking_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_input',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, help_text='Enter contact number', max_length=31),
        ),
        migrations.AddField(
            model_name='hotel_input',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hotel_input',
            name='number_of_adults',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0),
        ),
        migrations.AddField(
            model_name='hotel_input',
            name='number_of_children',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', '1'), ('2', '2')], default=0),
        ),
    ]
