# Generated by Django 2.1.7 on 2019-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20190414_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_input',
            name='number_of_adults',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0),
        ),
        migrations.AlterField(
            model_name='hotel_input',
            name='number_of_children',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0),
        ),
    ]
