# Generated by Django 2.1.7 on 2019-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20190414_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_input',
            name='contact',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
