# Generated by Django 2.1.7 on 2019-04-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20190414_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_input',
            old_name='booking_id',
            new_name='booking_number',
        ),
    ]
