# Generated by Django 2.1.7 on 2019-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20190415_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_input',
            name='number_of_adults',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], default=0),
        ),
    ]
